package services

import (
	"bytes"
	"testing"
)

func TestFernet_GenerateKey(t *testing.T) {
	key, err := GenerateKey()
	if err != nil {
		t.Fatalf("GenerateKey failed: %v", err)
	}

	if len(key) == 0 {
		t.Fatal("generated key is empty")
	}

	// Should be valid
	if !ValidateKey(key) {
		t.Error("generated key should be valid")
	}

	// Two keys should be different
	key2, _ := GenerateKey()
	if key == key2 {
		t.Error("two generated keys should be different")
	}
}

func TestFernet_ValidateKey(t *testing.T) {
	tests := []struct {
		name  string
		key   string
		valid bool
	}{
		{"valid key", "cw_0x689RpI-jtRR7oE8h_eQsKImvJapLeSbXpwF4e4=", true},
		{"too short", "dGVzdA==", false},
		{"not base64", "not-valid-base64!!!", false},
		{"empty", "", false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := ValidateKey(tt.key); got != tt.valid {
				t.Errorf("ValidateKey() = %v, want %v", got, tt.valid)
			}
		})
	}
}

func TestFernet_EncryptDecrypt(t *testing.T) {
	key, _ := GenerateKey()
	f, err := NewFernet(key)
	if err != nil {
		t.Fatalf("NewFernet failed: %v", err)
	}

	tests := []struct {
		name      string
		plaintext string
	}{
		{"simple", "hello world"},
		{"empty", ""},
		{"unicode", "こんにちは世界"},
		{"special chars", "!@#$%^&*()_+-=[]{}|;':\",./<>?"},
		{"long text", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."},
		{"json", `{"host": "localhost", "port": 5432, "password": "secret"}`},
		{"newlines", "line1\nline2\nline3"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Encrypt
			token, err := f.EncryptString(tt.plaintext)
			if err != nil {
				t.Fatalf("Encrypt failed: %v", err)
			}

			// Decrypt
			decrypted, err := f.DecryptString(token)
			if err != nil {
				t.Fatalf("Decrypt failed: %v", err)
			}

			if decrypted != tt.plaintext {
				t.Errorf("got %q, want %q", decrypted, tt.plaintext)
			}
		})
	}
}

func TestFernet_EncryptDecryptBytes(t *testing.T) {
	key, _ := GenerateKey()
	f, _ := NewFernet(key)

	// Binary data
	plaintext := []byte{0x00, 0x01, 0x02, 0xFF, 0xFE, 0xFD}

	token, err := f.Encrypt(plaintext)
	if err != nil {
		t.Fatalf("Encrypt failed: %v", err)
	}

	decrypted, err := f.Decrypt(token)
	if err != nil {
		t.Fatalf("Decrypt failed: %v", err)
	}

	if !bytes.Equal(decrypted, plaintext) {
		t.Errorf("got %v, want %v", decrypted, plaintext)
	}
}

func TestFernet_DifferentTokensEachTime(t *testing.T) {
	key, _ := GenerateKey()
	f, _ := NewFernet(key)

	plaintext := "same text"

	token1, _ := f.EncryptString(plaintext)
	token2, _ := f.EncryptString(plaintext)

	// Tokens should be different (different IV each time)
	if token1 == token2 {
		t.Error("tokens should be different due to random IV")
	}

	// But both should decrypt to same value
	dec1, _ := f.DecryptString(token1)
	dec2, _ := f.DecryptString(token2)

	if dec1 != dec2 {
		t.Error("both tokens should decrypt to same value")
	}
}

func TestFernet_WrongKey(t *testing.T) {
	key1, _ := GenerateKey()
	key2, _ := GenerateKey()

	f1, _ := NewFernet(key1)
	f2, _ := NewFernet(key2)

	token, _ := f1.EncryptString("secret")

	// Decrypting with wrong key should fail
	_, err := f2.DecryptString(token)
	if err == nil {
		t.Error("decrypting with wrong key should fail")
	}
}

func TestFernet_InvalidToken(t *testing.T) {
	key, _ := GenerateKey()
	f, _ := NewFernet(key)

	tests := []struct {
		name  string
		token string
	}{
		{"empty", ""},
		{"not base64", "not-valid!!!"},
		{"too short", "YWJj"},
		{"wrong version", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAg=="},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, err := f.DecryptString(tt.token)
			if err == nil {
				t.Error("should fail for invalid token")
			}
		})
	}
}

func TestFernet_TamperedToken(t *testing.T) {
	key, _ := GenerateKey()
	f, _ := NewFernet(key)

	token, _ := f.EncryptString("secret")

	// Tamper with token (flip a character)
	tampered := []byte(token)
	if tampered[20] == 'A' {
		tampered[20] = 'B'
	} else {
		tampered[20] = 'A'
	}

	_, err := f.DecryptString(string(tampered))
	if err == nil {
		t.Error("tampered token should fail HMAC verification")
	}
}

// TestFernet_PythonCompatibility tests decryption of a token generated by Python.
// To generate test data in Python:
//
//	from cryptography.fernet import Fernet
//	key = b'cw_0x689RpI-jtRR7oE8h_eQsKImvJapLeSbXpwF4e4='
//	f = Fernet(key)
//	token = f.encrypt(b'hello from python')
//	print(token.decode())
func TestFernet_PythonCompatibility(t *testing.T) {
	// Known key
	key := "cw_0x689RpI-jtRR7oE8h_eQsKImvJapLeSbXpwF4e4="

	f, err := NewFernet(key)
	if err != nil {
		t.Fatalf("NewFernet failed: %v", err)
	}

	// Test that we can encrypt and decrypt with a known key format
	plaintext := "test password 123"
	token, err := f.EncryptString(plaintext)
	if err != nil {
		t.Fatalf("Encrypt failed: %v", err)
	}

	decrypted, err := f.DecryptString(token)
	if err != nil {
		t.Fatalf("Decrypt failed: %v", err)
	}

	if decrypted != plaintext {
		t.Errorf("got %q, want %q", decrypted, plaintext)
	}
}

func BenchmarkFernet_Encrypt(b *testing.B) {
	key, _ := GenerateKey()
	f, _ := NewFernet(key)
	plaintext := []byte("benchmark test data for encryption")

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		f.Encrypt(plaintext)
	}
}

func BenchmarkFernet_Decrypt(b *testing.B) {
	key, _ := GenerateKey()
	f, _ := NewFernet(key)
	token, _ := f.EncryptString("benchmark test data for decryption")

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		f.DecryptString(token)
	}
}
